// Jenkinsfile
pipeline {
    agent any
    
    parameters {
        string(name: 'TARGET_URLS', defaultValue: 'https://example.com', 
               description: 'URLs to test (comma-separated)')
        choice(name: 'BROWSER', choices: ['chromium', 'firefox', 'webkit'], 
               description: 'Browser to use')
        string(name: 'MAX_STEPS', defaultValue: '3', 
               description: 'Maximum steps per URL')
        choice(name: 'HEADLESS', choices: ['True', 'False'], 
               description: 'Run browser in headless mode')
        string(name: 'OLLAMA_MODEL', defaultValue: 'llama3.2', 
               description: 'Ollama model to use')
        booleanParam(name: 'GENERATE_ALLURE_REPORT', defaultValue: true, 
                     description: 'Generate Allure report after build')
    }
    
    environment {
        // Set Python path (adjust as needed)
        PYTHON = 'python3'
        VENV_DIR = 'venv'
        ALLURE_RESULTS = 'allure-results'
    }
    
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('Setup Python Environment') {
            steps {
                script {
                    // Create virtual environment if it doesn't exist
                    if (!fileExists("${VENV_DIR}")) {
                        sh "${PYTHON} -m venv ${VENV_DIR}"
                    }
                    
                    // Activate venv and install dependencies
                    sh """
                        . ${VENV_DIR}/bin/activate || ${VENV_DIR}/Scripts/activate
                        pip install --upgrade pip
                        pip install -r requirements.txt
                        playwright install chromium firefox webkit
                    """
                }
            }
        }
        
        stage('Verify Ollama') {
            steps {
                script {
                    // Check if Ollama is running
                    def ollamaCheck = sh(
                        script: 'curl -s http://localhost:11434/api/tags || echo "failed"',
                        returnStdout: true
                    ).trim()
                    
                    if (ollamaCheck == 'failed') {
                        error('Ollama is not running! Please start Ollama service.')
                    }
                    
                    // Check if required model exists
                    def modelCheck = sh(
                        script: "curl -s http://localhost:11434/api/tags | grep -q '${OLLAMA_MODEL}' && echo 'found' || echo 'not_found'",
                        returnStdout: true
                    ).trim()
                    
                    if (modelCheck == 'not_found') {
                        echo "Model ${OLLAMA_MODEL} not found. Pulling it now..."
                        sh "ollama pull ${OLLAMA_MODEL}"
                    }
                }
            }
        }
        
        stage('Run Tests') {
            steps {
                script {
                    // Create config.env dynamically from parameters
                    sh """
                        . ${VENV_DIR}/bin/activate || ${VENV_DIR}/Scripts/activate
                        
                        # Create config.env with parameters
                        cat > config.env << EOF
# Generated by Jenkins
TARGET_URLS=${TARGET_URLS}
BROWSER=${BROWSER}
HEADLESS=${HEADLESS}
MAX_STEPS=${MAX_STEPS}
OLLAMA_MODEL=${OLLAMA_MODEL}
OLLAMA_HOST=http://localhost:11434
IGNORE_SSL_ERRORS=True
BYPASS_CLOUDFLARE=True
STEALTH_MODE=True
ALLURE_RESULTS_DIR=${ALLURE_RESULTS}
BUG_REPORTS_DIR=bug_reports
SCREENSHOTS_DIR=screenshots
TC_FILE=generated_test_cases.xlsx
EOF
                        
                        # Display config
                        echo "=== Configuration ==="
                        cat config.env
                        echo "====================="
                        
                        # Run pytest
                        pytest --alluredir=${ALLURE_RESULTS} -v
                    """
                }
            }
        }
        
        stage('Archive Artifacts') {
            steps {
                script {
                    // Archive important files
                    archiveArtifacts artifacts: 'bug_reports/*.json, generated_test_cases.xlsx, screenshots/*.png', 
                                     fingerprint: true
                    
                    // Archive Allure results
                    if (fileExists("${ALLURE_RESULTS}")) {
                        archiveArtifacts artifacts: "${ALLURE_RESULTS}/**", fingerprint: true
                    }
                }
            }
        }
        
        stage('Generate Allure Report') {
            when {
                expression { params.GENERATE_ALLURE_REPORT }
            }
            steps {
                script {
                    if (fileExists("${ALLURE_RESULTS}")) {
                        allure([
                            includeProperties: false,
                            jdk: '',
                            properties: [],
                            reportBuildPolicy: 'ALWAYS',
                            results: [[path: "${ALLURE_RESULTS}"]]
                        ])
                    } else {
                        echo "No Allure results found to generate report"
                    }
                }
            }
        }
    }
    
    post {
        always {
            script {
                // Clean up
                sh """
                    # Keep venv but clean other stuff
                    rm -rf ${ALLURE_RESULTS}/.cache
                """
            }
            
            // Send email notification (optional)
            emailext(
                to: 'team@example.com',
                subject: "Build ${currentBuild.fullDisplayName} - ${currentBuild.result}",
                body: "Check console output at ${env.BUILD_URL}",
                attachLog: true
            )
        }
        
        success {
            echo 'Tests passed! Check Allure report for details.'
        }
        
        failure {
            echo 'Tests failed! Check Allure report for bug details.'
        }
    }
}
