# tests/test_generated_tcs.py
#
# FIX: Scans most recent TC run folder at test time (not collection time)
# so TCs generated by run_agents.py are always picked up correctly.

import pytest
import allure
import os
import json


def _find_latest_tcs() -> tuple:
    """
    Find TCs from the most recently modified run subfolder.
    Returns (run_id, tc_file_path, tc_list).
    """
    tc_base = "generated_test_cases"

    if not os.path.isdir(tc_base):
        return None, None, []

    # Find all run subfolders sorted by most recent
    subfolders = sorted([
        d for d in os.listdir(tc_base)
        if os.path.isdir(os.path.join(tc_base, d))
    ], reverse=True)

    for folder in subfolders:
        tc_file = os.path.join(tc_base, folder, "test_cases.xlsx")
        if os.path.exists(tc_file):
            try:
                import pandas as pd
                df = pd.read_excel(tc_file)
                df = df.drop_duplicates(subset="TestID", keep="last")
                tcs = df.to_dict("records")
                if tcs:
                    print(f"[TC] Loaded {len(tcs)} TCs from run {folder}")
                    return folder, tc_file, tcs
            except Exception as e:
                print(f"[TC] Could not load {tc_file}: {e}")

    return None, None, []


def _load_tcs() -> tuple:
    """Load TCs — try current run first, fall back to latest run."""
    try:
        from run_context import RUN_ID, TC_RUN_FILE
        if os.path.exists(TC_RUN_FILE):
            import pandas as pd
            df = pd.read_excel(TC_RUN_FILE)
            df = df.drop_duplicates(subset="TestID", keep="last")
            tcs = df.to_dict("records")
            if tcs:
                print(f"[TC] Loaded {len(tcs)} TCs from run {RUN_ID}")
                return RUN_ID, tcs
    except Exception as e:
        print(f"[TC] run_context error: {e}")

    # Fall back to most recent run
    run_id, _, tcs = _find_latest_tcs()
    return run_id, tcs


def pytest_generate_tests(metafunc):
    if "tc_row" in metafunc.fixturenames:
        run_id, tcs = _load_tcs()
        if tcs:
            metafunc.parametrize(
                "tc_row",
                tcs,
                ids=[str(tc.get("TestID", f"TC_{i}")) for i, tc in enumerate(tcs)],
            )
        else:
            metafunc.parametrize("tc_row", [None], ids=["no_tcs_yet"])


@allure.feature("AI Generated Test Cases")
def test_generated_tc(tc_row):
    """One Allure test per AI-generated TC."""
    if tc_row is None:
        pytest.skip("No TCs generated yet — run test_run_ai_agents first.")

    run_id     = str(tc_row.get("RunID",          "unknown"))
    tc_id      = str(tc_row.get("TestID",         "Unknown"))
    title      = str(tc_row.get("Title",           "Untitled TC"))
    steps_text = str(tc_row.get("Steps",           "No steps"))
    expected   = str(tc_row.get("ExpectedResult",  "No expected result"))
    url        = str(tc_row.get("URL",             ""))
    created_at = str(tc_row.get("CreatedAt",       ""))

    allure.dynamic.story(f"Run: {run_id}")
    allure.dynamic.title(f"{tc_id}: {title}")
    allure.dynamic.description(
        f"**Run ID:** {run_id}\n\n"
        f"**URL:** {url}\n\n"
        f"**Steps:** {steps_text}\n\n"
        f"**Expected:** {expected}\n\n"
        f"**Generated:** {created_at}"
    )
    allure.dynamic.severity(allure.severity_level.NORMAL)
    allure.dynamic.tag(f"run:{run_id}")
    allure.dynamic.tag(f"url:{url[:40]}")

    allure.attach(
        json.dumps(dict(tc_row), indent=2, default=str),
        name=f"TC Details - {tc_id}",
        attachment_type=allure.attachment_type.JSON,
    )

    with allure.step(f"Test case: {title}"):
        with allure.step(f"URL: {url}"):
            allure.attach(url, name="Target URL",
                          attachment_type=allure.attachment_type.TEXT)
        with allure.step(f"Steps: {steps_text}"):
            allure.attach(steps_text, name="Steps",
                          attachment_type=allure.attachment_type.TEXT)
        with allure.step(f"Expected: {expected}"):
            allure.attach(expected, name="Expected Result",
                          attachment_type=allure.attachment_type.TEXT)

    assert title,      "TC must have a title"
    assert steps_text, "TC must have steps"
    assert expected,   "TC must have an expected result"
