# tests/test_generated_tcs.py
#
# FIX: Load TCs at EXECUTION time not collection time.
# run_agents.py runs BEFORE this test executes, so TC file exists by then.

import pytest
import allure
import os
import json


def _get_current_run_id() -> str:
    try:
        from run_context import RUN_ID
        return RUN_ID
    except Exception:
        return None


def _load_tcs_for_run(run_id: str) -> list:
    """Load TCs from a specific run's Excel file."""
    tc_file = os.path.join("generated_test_cases", run_id, "test_cases.xlsx")
    if not os.path.exists(tc_file):
        print(f"[TC] No TC file for run {run_id}: {tc_file}")
        return []
    try:
        import pandas as pd
        df  = pd.read_excel(tc_file)
        df  = df.drop_duplicates(subset="TestID", keep="last")
        tcs = df.to_dict("records")
        print(f"[TC] Loaded {len(tcs)} TCs from run {run_id}")
        return tcs
    except Exception as e:
        print(f"[TC] Could not load {tc_file}: {e}")
        return []


def _load_most_recent_tcs() -> tuple:
    """Fallback: find most recent TC run folder."""
    tc_base = "generated_test_cases"
    if not os.path.isdir(tc_base):
        return None, []

    subfolders = sorted([
        d for d in os.listdir(tc_base)
        if os.path.isdir(os.path.join(tc_base, d))
    ], reverse=True)

    for folder in subfolders:
        tcs = _load_tcs_for_run(folder)
        if tcs:
            return folder, tcs

    return None, []


def pytest_generate_tests(metafunc):
    if "tc_row" in metafunc.fixturenames:
        # Single placeholder at collection time
        # Actual TCs loaded at execution time
        metafunc.parametrize("tc_row", ["__load_at_runtime__"],
                             ids=["generated_tcs"])


@allure.feature("AI Generated Test Cases")
def test_generated_tc(tc_row):
    """
    Dynamically loads TCs at execution time — after run_agents.py has run.
    Shows one Allure entry per generated TC.
    """
    # Load TCs NOW (at execution time)
    run_id = _get_current_run_id()
    tcs    = _load_tcs_for_run(run_id) if run_id else []

    # If current run has no TCs yet, try most recent run
    if not tcs:
        run_id, tcs = _load_most_recent_tcs()

    if not tcs:
        pytest.skip("No TCs generated yet — run test_run_ai_agents first.")

    allure.dynamic.story(f"Run: {run_id}")
    allure.dynamic.title(f"AI Generated Test Cases - {len(tcs)} TCs (run {run_id})")
    allure.dynamic.description(
        f"**Run ID:** {run_id}\n\n"
        f"**Total TCs generated:** {len(tcs)}\n\n"
        f"All test cases generated by the AI agent for this run."
    )

    # Report each TC as an Allure step
    for tc in tcs:
        tc_id      = str(tc.get("TestID",        "Unknown"))
        title      = str(tc.get("Title",          "Untitled"))
        steps_text = str(tc.get("Steps",          "No steps"))
        expected   = str(tc.get("ExpectedResult", "No expected result"))
        url        = str(tc.get("URL",            ""))
        created_at = str(tc.get("CreatedAt",      ""))

        with allure.step(f"{tc_id}: {title}"):
            allure.attach(
                f"URL: {url}\n\nSteps:\n{steps_text}\n\nExpected:\n{expected}\n\nGenerated: {created_at}",
                name=f"TC Details - {tc_id}",
                attachment_type=allure.attachment_type.TEXT,
            )
            allure.attach(
                json.dumps(dict(tc), indent=2, default=str),
                name=f"TC JSON - {tc_id}",
                attachment_type=allure.attachment_type.JSON,
            )

    # Attach full TC list as CSV
    try:
        csv_lines = ["TestID,Title,Steps,ExpectedResult,URL"]
        for tc in tcs:
            def esc(v): return f'"{v}"' if "," in str(v) else str(v)
            csv_lines.append(
                f"{esc(tc.get('TestID',''))},{esc(tc.get('Title',''))},"
                f"{esc(tc.get('Steps',''))},{esc(tc.get('ExpectedResult',''))},"
                f"{esc(tc.get('URL',''))}"
            )
        allure.attach(
            "\n".join(csv_lines),
            name=f"All TCs - {len(tcs)} test cases",
            attachment_type=allure.attachment_type.CSV,
        )
    except Exception as e:
        print(f"[WARN] CSV attach failed: {e}")

    # Pass — TCs are informational, not failures
    assert len(tcs) > 0, "No TCs were generated"
